# Generated by Django 2.1.4 on 2018-12-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trellotokens',
            old_name='token',
            new_name='api_key',
        ),
        migrations.AlterField(
            model_name='trellotokens',
            name='token_secret',
            field=models.CharField(max_length=200),
        ),
    ]
