# Generated by Django 2.1.4 on 2018-12-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181223_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trellotokens',
            old_name='token_secret',
            new_name='api_secret',
        ),
    ]
