# Generated by Django 2.1.4 on 2018-12-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20181223_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trellotokens',
            old_name='api_secret',
            new_name='token',
        ),
    ]
