# Generated by Django 2.1.4 on 2018-12-24 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20181224_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='trellotokens',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
