# Generated by Django 2.1.4 on 2018-12-25 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_trellotokens_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trellotokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
